/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.KelolaRuangan;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import main.MenuUtama;
import static main.MenuUtama.namaPetugas;
import model.Ruangan;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Java
 */
public class ValueRuangan extends javax.swing.JFrame {

    List<Ruangan> records = new ArrayList<Ruangan>();
    controller.ControllerRuangan as;

    /**
     * Creates new form FormTabel
     */
    public ValueRuangan() {

        initComponents();
        as = new KelolaRuangan() {
        };
        this.statusAwal();
        kondisi();
        setExtendedState(MAXIMIZED_BOTH);
        update.setEnabled(false);
        detail.setEnabled(false);

        tabel.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                int row = tabel.getSelectedRow();
            }
        });
    }

    void kondisi() {
        if (namaPetugas.getText().equals("Tata Usaha")) {
            tambah.setVisible(false);
            update.setVisible(false);
            hapus.setVisible(false);
            laporan.setVisible(false);
            print.setVisible(false);
        } else if (namaPetugas.getText().equals("Petugas Lapangan")) {
            hapus.setVisible(false);
            laporan.setVisible(false);
            print.setVisible(false);

        } else if (namaPetugas.getText().equals("Petugas Logistik")) {
            hapus.setVisible(false);
            r.setVisible(true);
            tambah.setVisible(false);
            update.setVisible(false);
            hapus.setVisible(false);
            laporan.setVisible(false);
            print.setVisible(false);

        } else if (namaPetugas.getText().equals("Petugas Sarana")) {
            update.setVisible(false);
            tambah.setVisible(false);
        }

    }

    void isiTabel() {
        Object data[][] = new Object[records.size()][5];
        int x = 0;
        for (Ruangan b : records) {
            data[x][0] = b.getIdRuangan();
            data[x][1] = b.getNamaRuangan();
            data[x][2] = b.getJenisRuangan();
            data[x][3] = b.getLokasi();
            data[x][4] = b.getNamaPetugas();
            x++;
        }
        String judul[] = {"ID", "Nama", "Jenis", "Lokasi", "Nama Petugas"};
        tabel.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(tabel);
    }

    void loadAsset() {
        try {
            records = as.getAll();
        } catch (SQLException ex) {
        }
    }

    void statusAwal() {
        this.loadAsset();
        this.isiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        detail = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        halaman = new javax.swing.JMenu();
        subHalaman = new javax.swing.JMenuItem();
        asset = new javax.swing.JMenu();
        subAsset = new javax.swing.JMenuItem();
        r = new javax.swing.JMenu();
        subRuangan = new javax.swing.JMenuItem();
        Perawatan = new javax.swing.JMenu();
        subPerawatan = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Manajemen Asset Sekolah");
        setIconImage(new ImageIcon(getClass().getResource("../Icons/Diamond.png")).getImage());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_16.png"))); // NOI18N
        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/zoom_16.png"))); // NOI18N

        cari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setText("Pengelolaan Ruangan");

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow_up_16.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete_16.png"))); // NOI18N
        hapus.setText("Delete");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        detail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/info_16.png"))); // NOI18N
        detail.setText("Detail");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });

        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/print_16_1.png"))); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        halaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/house.png"))); // NOI18N
        halaman.setText("Halaman Utama");

        subHalaman.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        subHalaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/box_open.png"))); // NOI18N
        subHalaman.setText("Halaman Utama");
        subHalaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subHalamanActionPerformed(evt);
            }
        });
        halaman.add(subHalaman);

        jMenuBar1.add(halaman);

        asset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/box_closed.png"))); // NOI18N
        asset.setText("Asset");

        subAsset.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        subAsset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/box_open.png"))); // NOI18N
        subAsset.setText("Asset");
        subAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subAssetActionPerformed(evt);
            }
        });
        asset.add(subAsset);

        jMenuBar1.add(asset);

        r.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/door.png"))); // NOI18N
        r.setText("Ruangan");

        subRuangan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        subRuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/door_open.png"))); // NOI18N
        subRuangan.setText("Ruangan");
        subRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subRuanganActionPerformed(evt);
            }
        });
        r.add(subRuangan);

        jMenuBar1.add(r);

        Perawatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/toolbox.png"))); // NOI18N
        Perawatan.setText("Perawatan");

        subPerawatan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        subPerawatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/wrench.png"))); // NOI18N
        subPerawatan.setText("Perawatan");
        subPerawatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subPerawatanActionPerformed(evt);
            }
        });
        Perawatan.add(subPerawatan);

        laporan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/paste_plain.png"))); // NOI18N
        laporan.setText("Laporan");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        Perawatan.add(laporan);

        jMenuBar1.add(Perawatan);

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/help.png"))); // NOI18N
        help.setText("Help");

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sub-help.png"))); // NOI18N
        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        help.add(about);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(print)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detail, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapus)
                        .addGap(21, 21, 21)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cari, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(update)
                    .addComponent(hapus)
                    .addComponent(detail)
                    .addComponent(print))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        TambahRuangan tambah = new TambahRuangan();
        tambah.setVisible(true);
        tambah.petugas.setText(namaPetugas.getText());

    }//GEN-LAST:event_tambahActionPerformed

    private void subHalamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subHalamanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuUtama utama = new MenuUtama();
        utama.setVisible(true);
    }//GEN-LAST:event_subHalamanActionPerformed

    private void subAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subAssetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ValueAsset asset = new ValueAsset();
        asset.setVisible(true);
    }//GEN-LAST:event_subAssetActionPerformed

    private void subRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subRuanganActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ValueRuangan ruangan = new ValueRuangan();
        ruangan.setVisible(true);

    }//GEN-LAST:event_subRuanganActionPerformed

    private void subPerawatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subPerawatanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ValuePerawatan perawatan = new ValuePerawatan();
        perawatan.setVisible(true);
    }//GEN-LAST:event_subPerawatanActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Laporan laporan = new Laporan();
        laporan.setVisible(true);
    }//GEN-LAST:event_laporanActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        UpdateRuangan t = new UpdateRuangan();
        Ruangan b = records.get(tabel.getSelectedRow());
        t.id.setText(String.valueOf(b.getIdRuangan()));
        t.nama.setText(b.getNamaRuangan());
        t.lokasi.setText(b.getLokasi());
        t.jenis.setText(b.getJenisRuangan());
        t.petugas.setText(b.getNamaPetugas());
        t.setVisible(true);

    }//GEN-LAST:event_updateActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
//         TODO add your handling code here  
        try {
            // TODO add your handling code here:
            if (JOptionPane.showConfirmDialog(this, "Anda yakin untuk Menghapus data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                Ruangan b = records.get(tabel.getSelectedRow());
                as.delete(b.getIdRuangan());
                this.statusAwal();
            } else {
                this.loadAsset();
                this.isiTabel();
            }
        } catch (SQLException ex) {
            Logger.getLogger(TambahAsset.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_hapusActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
//        // TODO add your handling code here:
        RincianRuangan r = new RincianRuangan(this, rootPaneCheckingEnabled);
        Ruangan b = records.get(tabel.getSelectedRow());
        r.id.setText(String.valueOf(b.getIdRuangan()));
        r.jenis.setText(b.getJenisRuangan());
        r.nama.setText(b.getNamaRuangan());
        r.lokasi.setText(b.getLokasi());
        r.petugas.setText(b.getNamaPetugas());
        r.setVisible(true);
    }//GEN-LAST:event_detailActionPerformed

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:
        if (cari.getText().equals("")) {
            this.statusAwal();
        } else {
            try {
                records = as.getSearch(cari.getText());
                this.isiTabel();
            } catch (SQLException ex) {
                Logger.getLogger(ValueRuangan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cariKeyReleased

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jasper = JasperFillManager.fillReport(
                    "src/Report/Manajemen_Ruangan.jasper", null,
                    koneksi.Connection.getConnection());
            JasperViewer.viewReport(jasper, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_printActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        update.setEnabled(true);
        detail.setEnabled(true);
    }//GEN-LAST:event_tabelMouseClicked

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ValueRuangan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Perawatan;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenu asset;
    private javax.swing.JTextField cari;
    private javax.swing.JButton detail;
    private javax.swing.JMenu halaman;
    public static javax.swing.JButton hapus;
    private javax.swing.JMenu help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem laporan;
    private javax.swing.JButton print;
    private javax.swing.JMenu r;
    private javax.swing.JMenuItem subAsset;
    private javax.swing.JMenuItem subHalaman;
    private javax.swing.JMenuItem subPerawatan;
    private javax.swing.JMenuItem subRuangan;
    public static javax.swing.JTable tabel;
    public static javax.swing.JButton tambah;
    public static javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
